[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "a3437a38fcf902e102afc52e9e9a7a5855aa0520"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9082aca21c4935a4403b3d129ed7701676f0fb5c73200ed64f696717c10113e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbd3a31fcdf23603bb81aeb5105a2eee503b83a2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "36120b2c1e8c64e863da67a0aca476b35626fb54cb4dc2be40ab8d11c58a9181"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe6720f203ea7baad224e59aebb7fb2e8b30e7ec"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "be6a6d2ae4e3e67e2dedcecbb5ce673055c340847293186ad7431dddf6154a18"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5b6ea10605bef2ea0b314489d2a2644a6e46350"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1980abba4bddc432f0280755880f8d505373d9f4dd6b5f721e712740e5cc130d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "727e3232008df84b5d650b0a30f52c99e76d6bc2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d2af7c3d74f51a88f6639d3c61ddb4f899fe2cf675fe7ba11410be909cfa449b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1befd8d7a9e9154967c57840c6ab63c2c54e3571"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f816dbb0e3a93145e293b66dcbed606fe8171e88c85caf3ae7455b3ca4a9e8a7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff53f66a1c117bb6605df46e3a06a49fcd4c5d8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6bfad0ea5c5871c702c3b29667ff434ad4cc5944e3d8d969725b9576a4100cf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5bc6d2eaf95b4ec02e28bfdbcfa509976bdd1f7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d2d9f5b84b74b0d4d33fd3f587279455df2fccf4d747ba4dceedfa5a57500813"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fd91b49079fad6bfb860b2c2e61e2f2532ecbf3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4ae919f45f8e89552dc22455bcf498e6f6a9beabc6746efded62ce4946c907af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2e71f2fc37388198ff61773e85cf0069ed606d7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6e142c4a28f80c45d96c8ff7634849abfcdf53985b192cc5550959ff64dd8ad7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b33db153738bab3d75dc1709d1634c0e21b39aa5"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f6ca4f468956bf9bc4e46435a0d70466378eedf5d19ed6458a7152eab7a252e5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc331925dedb5536a661db4ca611ca80baee87eb"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "96d8798d6ff5cf6a7675c8aba44731dc2a486e1dfe69b5487c9c145839d2f53b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeec1ee4a60280e771dccb8b1b097bb893f1965e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "16761d100cedb6f1bfc98cbcd75ae213cb87c3d5b6f0aab91792f81ae9d5c38f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e02b1f637040f9f1a494d80fc3dbb7d808c3432e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "74afe8fbafa73216882cc1d5d29e840bfdcaaae8c60f1b1f8c74cdced8e0c738"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79060df05d504d4eed37e37b28f624987d93b457"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1e5d02580e0ee1f43bd2a15be41266f40d7b66546390b1ac48567d31734bd920"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40eaaa8a01207dced4e02480a1045fee77d2204b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c4fb32be56063444eb29987910c68d7497953cb17e1d4f5ddfb55414f505e62d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a95f1bb3c2182eb461b405e3ac64aa51bd8d442a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "77c212a6025892fc32091352dfd14cfbedb28df7b31a8957810f2283d848dc76"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac9ab8eb17112dea8fcb1406fdc775495f58e6c8"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "36e8502d703a40a5e6d91d90c565220c8d3cdfeeb341efe1cda6e8681e93feb0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "624f04ebcd150da3a0fd6df2531283d6a0bce0cf"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d43182790bb3c22af382298af3422e1b82e8ae2f851e6e28275a0d6668773d06"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "980112bc864f8fb7802d0912f4d472be46edd6e9"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "967841aad70f49122a444cfe15c3460ca41d9b470776d65d1f37a2d03545bdf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b858f3e8c939c3d5405ee9e266156cb2f64daa3f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4080091aa5f27acd85f9b1ca29b578e314d2259e282bd169e2bb2f388286c179"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "9e7cf6795382ac5f7ceb9aa3163bc36316243630"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9c51915b96a55d30576006d2608aa73381c8da27db5a009735b5700997ad8c31"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5167cf231ed6683926a63162bfe63e15a33713bd"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8097deadc985c663917f0ccb5040c1bdbad04c12c2b94c52d474def152ccd171"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b55e6b42e5f7b8ffca70f64bc32a8ee7632ccec9"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1e8786554ea86cf0dcc8da3d52003e91e6f1eea96ab92269debdc143664cd71f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ab96eef177306c59ac8bf9ddb203dd89403c349"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1c53b06e5d694283ae33606029c9022b49b721cf12fb3d9d51d52de96a5ee4c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30cd7d51cf1676d62a728bf8fe983a50272a5b44"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1ea03dbfe76920698e3c381652e87686b52c11b7dc5ccbbb4ba12f4ed2b52b80"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "de72fd36a90ea2b312ca1a035f25d9ce4315dd90"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "c547d762e56b8987c231346a883dd834a314007c6747225df09367b560357c2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60b88859d9cd258abfaf598710f81bc280706b3b"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "29a66f09cc9271196547bc21802ff496d9df2382ca400bcf994a70a3f4d2ffab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73ae1c61156c4c304458ddc3d31060fb65e6bc8c"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "a469b79507db24d892f6c03162240b11a349c7bd7bd6efcaef5a040d1693271e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+2/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
