[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "63904424c96c9172d5e626bda85a6ddcdadcd1c9"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "e003756c6b89794c2c68ba9bd3e7c31da5d94278b887a0dbcf185775f212bed6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8087183d5cd64cab0fb720463b8261b27e4e35b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8e1c18bce4ee49e0e196c08fc5ffab0af8bf606e3e64ab4b45c1940e00f4feeb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73feecd0b2c940dfbb26e0125bb28e067296f4f8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "58b56467fcf750b757194f67266cccf1c765e3c05c47eddf7a4e1ca615f5959c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60684949f1e9de28fb1877c65def072f15bc82f1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "227e94347f365bd11b2b8b891bee956b6c9009fca3e4f81107f717f58ca547f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae16bc1eef9b4620137351d64dba0e46c6ce7183"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4fd1c6f6630d56402cffd3e510101c6b1da39e9fb3da4dfe8695902c0e3d98d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "543daf9209ffe4dd26a885c875d89b7aa241096e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8a1a5480d91edb75c4d63943ebb656bb1628480fdb2cfdf5d560f30f3e503c90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be3d7d67c76f95c5fd6f919111071e1bdb4cd807"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d1350472fc130e802eeda74844e639b16191a36b292ef947317590126d4538c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ae388de74dd75345de89ef7e4e33d298c47da9a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cb89497d6a9fc70a9e6d19969b2ab6c55c94301c9802cb62286bc1d0bb82e9d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "731638141c41b48471c2ca07715e6bbe742fcd01"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b4fa606f1580e8828f93a5f49e9eda3db8aa0b49e1d734074c08b67be46da57a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e708859746fc1da4572c940f03557b652da7c6d1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "11294acba69086762fd76323ea21c456081b82cae5e7dfd89b62fa9e44935232"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e89e8017656f18de73b4e3347e9e1df65076915b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ba486531ab46e214bcb745aa61cba4e699a80633ba8c519a504476af9772a971"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a9ce16b0f7fa7e8c201ffd9807fc2001982ceb7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "47ed0303d9938a8680cd7bd2fb11b6c48c2abf1cda846e689b32015bbd4097d8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba03897064a6fcbebaffb076dac4420089165315"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9f5ab2c1b95f4e3b9ec4fc5e5648ad26cb7b83c47f4ff9df1f21ef1b17ae306d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d8484638fa28b4fbbe8b2c0646afe22965e8d73"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d2320626173f5d423e36b5195a76984679c7f60fde059ac05a1f5170c3105a40"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de7bf47d25f8912a43e6aa6274cb4033f3075f9f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7c711476707732b53c48ae33e66588f989ce2249f6fda2d0102fb3cf5df55c4b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b8534baca077e5f028fb75c23462fc340df28c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ea0a604b4c601463364afb6467e84b78caf7c9c924639911169615e287fbaef9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52dd94c159917c51c4cae090c67d093d7bca3101"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "486db0932b700a1dcea07707408238d82668576babf8f5e8a2a5c85ff868bad2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6ca2a2613967c6dcab7f299896cda2f82c6b396"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "4e7f4d4f7d5096087136659df965c2dc44f335ccac92501e0b985d5c0220ebc2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d39f3ad696ac0c04575ca13ca770bdd1784ad76"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "7cef2995a2d83f522cc5b561e1a0eaec32639518b8c04b140212f1a685b93263"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62b74914085cc7c9e500e22b02590281aa136c6a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "06d94d4ac7a4ff308a8f88ae4707a6e2694f368c76dd30d4cb6d134906aa54d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f79826576c2571c0285aec818ce4cc50e2ae752"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2062a3b65fa76d5573cfe277c5390c8bcab3cf6af43db81cffab62247a651600"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "74815b2c53cbf4c850de43e1081b097d78aaa2f1"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "3310af2dcf0f35a222d1e431dcbb71ecb0b68df747fa3c65a9bf5dd5f44376eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4af2147151d17049ffbf073e7ef54fcd493fa3e1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "059dfa7c97e3542aa4f78c92255d81d4450f186f2288ae08d8207402c1f12e72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99345221c5a397491de07b79340fa58b9c3510c1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1df692ae21c847a63ba60dedcf6ba2c2dbeb3290275a1effe19cbb929ad0eb51"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b55e602ca51866d62bc049af2ca02aa45f94f226"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "86dd997a367ccb65e605b0480e7780e590bf069747a7246b02f77bd6a5650881"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1a17e4104ee17f644cb101d0f1055147e17006b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "35845c7992c57cd2d2db01d821cdc5dc3793e45c2af391f585281b10cbcdf001"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "f4582f95f84f4404e46a0e4c720780032848dbb7"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "0cda6ae946562e92c23ae16c26eecf793055bd45407011d14349d88bfc39f911"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06888563fe1c1d279357ae60208074a08689e258"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "8daf2efc31c0b1ca06d1d77f212bf13db61c3fc78d35c5883dc9e0573ecf0c3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a934a739e4981d70f121e6aca49545b3190d3748"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "a83036a4529716b3f3df1ef27a4479ebb2a73b8420b3f641edcf809db7cdb6f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+2/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
