[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "0ee9fb5bbcc12b7c1a4540c9c2e3ee8e0a6f983c"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "76ddad44f05d02a6cc022e9847664eddd88da5f6f5f04e2ff2e126ae71243348"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07011268a8ed22570964929bfc370d4e27dc16d8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "faf3dec8209e8a92936cc1bdf9c88451d9ccc1052186ee07326d2e0834bc825e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae3fb15d2980aaf136d41b85f7fcd9a94c52820a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "831c7c39b195a5c7a9adbfdf2200e9070410ec04a4513d9b55c6f268730c1016"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c14d114e0bdac875fb3e7f33d3ade785d724ddb8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "add38ad958c9145b2ceb2306ecd6b53aa0b4d28f8b3b6f47a2fd449f706ed82d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e428f177bf9bb47dab9b02322e0fc705bdc1bcdb"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2ffb8f12370a1bbd956b241a0324233034b06628bc6210e9d82ad9dedd88af03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1e556b77558b8cd9117c5e09338d8c8efcb2b6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c93fb90735cce5bf1a073ba4736388e64ff95a63b5db770b5e9cff2c970adc53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85edeeea54e8ff700fc45fbad9174f7bc047a8b0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "78164bff5023578863fd61c03265f16f5a36b9f7785be19c602c60f1eebb51e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f7a9a8df8cbfa084ee163c075e42710b94a353a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "eddaa1ea3b2050f74b1141d795524745f9f2e56697100aca89bb8d73a79d5b12"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "317f72003ebcbe1caa6d9a78cf630e99abfc80e3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a93ad458974e6117f0faf102520de08f5aa96e8d5f1dc65a2bd9f6499b16182f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "758a0a4e9ba1f970690846f9fc8e2db95fc794f2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7456ccede7c7561dd1c0d4681b11481873b0036710cf10a9b109a635bcd5cd0e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "007875bbe169d0b3020fddead26ea01e0e03c11f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e2ff3fa25c6c071406185ee4fbc096c97e1dc7c69c9640dd934efc1bc4421c04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b78c111ba6bea389b61746e828dad68e1e0a2fd2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "685500425355ce0afe2b6b541e0fe4283ce06fd176a4fcc63c51f5d60610bfb2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82c5ab61bf0e5ad156d561d479d047c41a313451"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5e71d389ff9a7f16b8c9a3baf590f3f36c2d1aac22c1df3b7c94211e008c6528"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e374c54863a8efc05e24c030f272c4ba972d124"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8b551a3eeb954d72dd800a1c7e266525029312163791c891268c8186afcc78cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03f97bd7ec87ae8ca3327f4ada5c59d9c6f29d25"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "55b2ef16d04a3208fa250b98bbd3587fb9d6a9bcf14f9f123562294c35b48149"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3aae2f7904b7870c2a3064e7a03c955f111d0e65"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ec42ede067a86171ef0bf8637ddaa0430cff441c00a9d3d32338d8c61f6006e7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b9a4b9c271d2f2714a642ff992c4e30063b636"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3c3c16444fd14f5b560db31e10f8f892e7bd7430f39e46a3f58da77451c45a4d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f5f5dc37128deedca6439024450f339b05bae5"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "ed97dc24acc0a8a88819bc64bfa913a413fa678c9c399844f175cf210b9f36bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6af20230705637c7db289f4c874e267e0ec05a3"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "e4d1179336cd4ad7a2bd33914d49bde98fe06b224ae09e95b5a69795683e2882"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b58fe2164e89bbddd69dd17af5a55649d8c1a4f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fb1db322f3c28c6ed4cdad9ecafa8490c0850e52f4793c2a873529d9538c7737"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f26cc045f1d81e4de5c2f8c73262b9c2b5e887a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cf3656818e6eceb9581eaf24911f300e6fed9df8a196430106b1b4adeae1757d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "cdc3040f483865c31cf31ab76376a31f51198cdb"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "4cf1d18ed45ef11b4b8adf9f45c9c3f8fffd5e4f20330953bca8d9f5f00cf670"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "093884151f97e1e5ec5c7dbf5a4f9cf01ed57dd0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "be6f5f3458dd8c62069efb31d858277c430a3e5bf8917d4acd7f60bb29cad706"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3134d59d6f2913eb614e80a35923ed821926cfdb"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9e8e59e42477892691ffde9481b98a117ae595adee23d71836c053292872e661"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a2b37da1e376ac13c8001a72525756c83d3c00"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3d959833caa4de72fd01ee947106116ad6c981f196b9dbae539d31ac871746fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ea43b9b5fa042481d207c652b6c5f960f888ee"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9b6666d2a61d5ad62bc831202f6e70c505ec7b9d3e28a7d174bd1b61e5c21f47"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "0dfe2eb2ffed9e95f28648b2de49654c5ffb4ea4"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "b5eff4e935a53f8d3a557d67058b6451ec51c0f405dc96fac20cc2d313f4a30e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "364cb2cf1185d99311943f71c643eef607785356"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "11a22205bee3409624262d8dd4e731a93ab4819b6d48487e2823d6a84dfe4a83"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31905b016d91f7e615b65b19841158fc9ed5b67d"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "3b4ebabc69e857ff1e1cad451810edd01793307723e0fadef9cbee83777c62f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+2/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
