[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "7c98847fb54664a878c6a80be17b5b28b6d88a3f"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "75bc6b64c3760be97532fd67898030011361cb7b6953b4e75ccf654ae858fcd2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd87c1805455c77c0d21b9370b599b2965b2ed4b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c480a81bdf1039b9b311cb0c7d7f5972dbc182e1eb82b8708dccabf3621b80d2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4078fb521c35e493739cdeb97baea6b33da569a8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c1ef0707f1a36d6e051c20984d309fe7ad9f03524b2032593d3299332c6c1020"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40a361c8653c7ade32e3fe8ea54a7db67504d5e1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "78ffe5a4aa719964ba4f548c04a6de30f758e952fbef194ba1a880f864633627"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dc50297726f06dc75571f3137ad737ebec161c4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f046eece8ac3e0936a1ef3b8c03a3a6094901858820f17453d5b01aad76185e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e91e82df271ed9030deeda95626c8e37e57b76d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f7a86029db3e264e32c4e7ee4b5d9fe77e1c60f681ab01e09ccd5d365fa34d07"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08ae1be43056291a8cf9aab2d8f789b9da64e796"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7d0900c47e3e917300d3ebf8dd3bf34ac6a1e8bf33a9867a371e57a4654b4913"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ed3a767c597dff31fea70926d079577bd946a99"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "562cd158b174e04d1b2ec7842dd2ba2c57faa4f7df09e51ddee2cbb5fc109121"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88c027456299ca8a03cc8f4ec288f07a7eb24651"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3f21b710724aae23efb6e0b76bb68ef5e77edf8d2ee19ddae93057a6e2accfa2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9ac458de0ec2b9ce4f8f821f0681d712a618ea5"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "90532733351d14f7a983fb71f4207cb6ecf0b2770f28af2a39bdd73a633c4a21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7dbcf8e897b4b7968d5b5b2dfbebe31ba281557"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "44ed29f47ecac83d16415a3967720172e2cd64153fd4d4cadd655cd83a81e602"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a7c7b715d9d6ed19ab0f073497b401aef54d239"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a357ad87bebf34e1bf3bb96da1c169435cdd201ceb496991c0685bd1e9a69bd3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5415ef7e6a05e05802a78e97529ef0331d50781f"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1cdeb75ce872d527cb1fc6e12077d40f494bdd9e2936d378c15099a2409144e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "953d15793d9f0078ffab0dbb1aa3a4a9c50375f0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fd6434c60246b9ca9c79cb0f9ceed976f0fa03f2fd1bcc1f074c93e0f8968114"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f91d884bebb15898580a3dfa2684b3002ed89f86"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cfa30c8d378ae6f9b66983f2684f5bb57c2a1ace37a63e76ac5a973b18c8baac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c57dfcf92516e96d2eaf2e34f3fc1ffdbc412aa"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "eca009018f57913e6ea03a69cd416a09df2d45e58c5a8e7829e18902a959f52a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02af47637c14d201b1bac3b87dbbb53817765a03"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a9471b6921308e326a288683599630874c2a2f3d7599f012dba023b4c01f5ce8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87a56832e0f125671522b50f76533b3e4843b818"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "49c6861aeadbf68be3a919174926cbc8ae196f4cb7d904cd5f514eaffdbbe324"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d14cad6fbc0f2fac380fa8b8d084221661239ef"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "ac9d1459fef98e1d06974fbb61d1a9b383bdfadbf653609f69a5a6c0c7bb687e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eca3ac436b4b79f382ee62d6bec6211ab8b2c17"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "940a4c066fa057185677d5ec53a197cd9a618636193cf0c9feb3d86ecc6f053b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "864deaf3d7efd6030e377c04a1561475dc1cf2aa"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e5fa998461b841db4b24f573843b59cec80ab5c1b299d491ff5e03d0810c6c96"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "a4cc414d242408c1f715b15d10d65e3d1a101e68"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "e39aa663d3ae6a0d5d2f0bc715ff3fa8c3a0ec659a9febd5ebd3f62ac2ffe4c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aacd359546fd2d386b52ae9c543b2cb2e56a59c3"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a9048a148c065a571d276b806bc99e8c5bfbb2700cbd378be664097230cd1231"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "410e1708bf60d5c8e380007bddcbf2eff9236a54"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "94bd490c4be969bbde9504d31edc709aa0a54de73a9982ac6d754f088053f386"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23aab3b58fb0b5a3f6117582158e1a9bf6ef6664"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0dd0d1095e1d2a4bace39c8db17db24f6e40004570e8982983fac0ffd5276fa8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d37cda3241e4a158991edca56b077b35defe6c4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5741dd966abab03b105fef22218582a9060cb06ccee9f14612f6dbfe36380d0a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "418c5b0f58530911b59a411857959381ba21a426"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "0683fba4d20485ab9121e63b9040a2c6cc3e5a6a2ba110ac6b8a697a78f657b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "346039ce54759b0e794219a0b8bfdc17a6db95a0"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "71a3e2e28fd02afb51bb2e656c25d2e872bc88d7fd871295e61c0e9d37605e80"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7ebc79610ecf5cfcdfc72d723f669eb86f297d9"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "6721160bb3e9195049e500ad8d785da0a1d792b02b3b6889e3013cd64c083e3c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+3/LLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
