[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "0ee9fb5bbcc12b7c1a4540c9c2e3ee8e0a6f983c"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "fc0ef2021871fd03dc0c5fdb03722afc051dde3dcab46c7b860ba51a138e7d65"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07011268a8ed22570964929bfc370d4e27dc16d8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cae94f7b49564aee49ff1e09fb4577c0e966b33ed18feea7e1ec715e976ca723"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae3fb15d2980aaf136d41b85f7fcd9a94c52820a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cc33657a5d647be755d3ec2190c2eab6c09f7e6238675046dcd7fed8ba589536"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c14d114e0bdac875fb3e7f33d3ade785d724ddb8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "844a5fbabc6b4d052ba39f013d8aef63cb50dbe4c208e9f878afb5416d8523cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e428f177bf9bb47dab9b02322e0fc705bdc1bcdb"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5ebfc3a3615aecc4ad05cb038b3dd50aab2ac216817c1dde74db025daff2e1c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1e556b77558b8cd9117c5e09338d8c8efcb2b6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4c4f1fef48d42b83d996f87be6952eccb5264075def937d865280e81af80201f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85edeeea54e8ff700fc45fbad9174f7bc047a8b0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c7a340f5dc1d4d68c5bcc50bd0893b61182c4f35cc8205eabf109a62412f9304"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f7a9a8df8cbfa084ee163c075e42710b94a353a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "029f61299ca79658be5214c6a869625564cb2076d6ab8a9794d101af9c69cea5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "317f72003ebcbe1caa6d9a78cf630e99abfc80e3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a803d2655661b28108303108ca218ba8ba0a6001f9dc73bb72848d15f7bf79b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "758a0a4e9ba1f970690846f9fc8e2db95fc794f2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8d58780203c91a95309aa5ab537a21570aec2dd54ae58f50f807d5b317c6fd1e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "007875bbe169d0b3020fddead26ea01e0e03c11f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cdb31cc85183e0f4b89cdeb68ee547ba3e1125fade72aebbfe04af11d3868d72"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b78c111ba6bea389b61746e828dad68e1e0a2fd2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cb60c1374443a428d8e3111b5800b7c736a1190ce315a498cbfc40497649c385"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82c5ab61bf0e5ad156d561d479d047c41a313451"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ed1fa55d47c73d7ca50aa7e12b2643db37e484a07d25065dd611888e0257e5a1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e374c54863a8efc05e24c030f272c4ba972d124"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "46954acb1e8c1c85e857ebd2c558231919bb9699379a19b7cc4a4ba0636be705"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03f97bd7ec87ae8ca3327f4ada5c59d9c6f29d25"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "765ccd7fcaa9a8b34b78ebf17840140e7a8f6fbd5fe95f3dce5804172c365b7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3aae2f7904b7870c2a3064e7a03c955f111d0e65"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f08b650005e4c35b091e5ab6312309be88d9e186bbe9cea333956dc2a602c00a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b9a4b9c271d2f2714a642ff992c4e30063b636"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3b1796b1da5feffa8fbbdb5bd258dbec46454c4391c4e24a47700056bf0f24f3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f5f5dc37128deedca6439024450f339b05bae5"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "7a8315d9e27a5703535c777d7970ed326f400f6bafc34d012132e7a85144f566"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6af20230705637c7db289f4c874e267e0ec05a3"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "2355471098e03f01c5815c6305dbd634a8d81a7e2a00e3b36388fc331e7ef31a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b58fe2164e89bbddd69dd17af5a55649d8c1a4f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9abef6fc301dff1514a4a05d1c872b53bd0e723a4c65dd7bcd370d34b337f161"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f26cc045f1d81e4de5c2f8c73262b9c2b5e887a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7cc6d8e5e72825fa763e3fc309b970cb073d013f97a9d9d93f576db328503329"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "cdc3040f483865c31cf31ab76376a31f51198cdb"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "fe41192a06cbeaa8673a893e854c47915721ab28738712a6cb57fc7d43d778bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "093884151f97e1e5ec5c7dbf5a4f9cf01ed57dd0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1832b386f01878af179d32c4a252521ff829ad8daed01c34531270108848125a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3134d59d6f2913eb614e80a35923ed821926cfdb"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2e0f28a8e63ce0f6ae75c894f41221b69040c8a921fa61b5eff1331741038243"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a2b37da1e376ac13c8001a72525756c83d3c00"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "26ce7c4d66eee112da891fe7d251ec7bb1e5d37dd1b76b23166690e39090d803"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ea43b9b5fa042481d207c652b6c5f960f888ee"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1e7de0bbb20c53f1378d0973c5077b5a69fe4a4fa1966a9fde146cc82425e99b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "0dfe2eb2ffed9e95f28648b2de49654c5ffb4ea4"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "7181685f25b05c7d3c0cff7b3b42930c06559413321329efcdc116c3f4d16f1d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "364cb2cf1185d99311943f71c643eef607785356"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "1a2a5846ff54ef0c911403aa4a0c48e0a1c88e7b55e62e4e4cb7a49a07b05a7d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31905b016d91f7e615b65b19841158fc9ed5b67d"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "754a84ab7c73f66615631a2fb197ce829087880fa9d3af8eb19f41c8a41a8caf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
