[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "1eeb7b219628e178c7225de98414b104be1f8c76"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "c17bed5d59aae8858a63a0491ed49ad327018fa6d8e0f28bbd6f8564e269cdbf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcdd86846d2402ca82852840e358f9c7dc934f02"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b03065633e089a423eff8e48baafb8c3706e5798ee293d85804e1050ce72e7e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95e6a0c061401b0d64c65feacddfd24fef0b19bf"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "989413fa167330291df4284d935a3410d246e9e28c8f0fe9dbe659f128a2c4f6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df2f02ba31e37bca6c475236554ea3b417088d23"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7a8bccc1b48d07cd1a7ea77e4bedfd577d39902518a78a31afa7578d3b79d962"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a14dffc791ccb679dc56a6bfe93084d742ab833"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5ec7b1f1d23d6fa333b02ea768928a74dc2d68c7d8e3b3ab4eb132e53dec196f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd014d0a51b6cd97b1541efc88fb4180416dd166"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c972977db662ed8dd776e317085dfb1c811a9753b056b981887c4dc1bfcfa819"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3ef9a46b6b299c3cfe073b91d82840b379571b2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4883040209e1cac09bedfa85a087cc62cf736358c43764b2c7c058e287f9db41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d6aa9f4a7a07fd092e2edc1bd5f8616c6e3ea3e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c985e2fb565841c7a531af2cc56b438c25b2ec3bd65696dfbeb5a4b37a3d2735"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbf753a7ccb68765048f1275fb07b0a583ed1801"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9333fd90a400e972e5661f47715a4be62f7d4c36c45709d3d37fdf079815b49b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18d55baae68909a11f36c8340f2299c90836ef25"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d33a1c2bc6e05c26975643342d70f8086776341949ae30286bb9a5c20f21fd5f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55a6f7cb6d24e706863ff09b3627d0ae11856779"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c19a8e685d4dea4adf2c8b92536d190740d1f3f1e936cba0d7c65ec290107eeb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a72eb968fb0040db1d93b7ca56ceefc9bd63cf7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e3cb361ea35b06e4e60ccc99678ea1232ca35821d0e771666d609da520c5b1ff"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8da3be4a0695348c04a96aac72849f103eb14054"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "175fb9afb5be109e3582e9bf4a9ff03ad0f67ac4fe747f1aa396742320b2eb35"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cde0d8667a634e2419dec1969cd8e799713454c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e5c44ae65f1391e657ef9ff0116321f259f3b14b1ccf5e9a6d6bc72ddfcc77f4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16a3c4a683a406c2e1f76d4050b42691723427ee"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "400f63344e275f0d5682af6b7cc6c4a0e90b0a98e776ac30ee70c054dde9ea17"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7b2dc03a44ab9d0bea4a3aa251732fb4f97102b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c4b3d732dac11066370d0596cf393ff379c850fab6ed9694a18045b0f8f909af"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8021ea8809923c3efb9619b06f2bdbf21287ceb0"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c54e943cb811eb334a067b593208f8cc87396b3266c2f3b1de44a2811824037f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da31c4956daba4b7812854e3bba4b78c825b5899"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "06010f47b64261bea174eef1f171f25a766952ba4c16afa761ca84da9a710d64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c9f82dc7a4adec55bea042edcf73b2f6adf570a"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "5af6a187b1b7fc9ceef871586ac6284eaf70e14038a6c95b15f90b98cb390a01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84f7069f65f420d19d0593d42957caf9e0f3d759"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8503b7893b9cc874c0b4f8d5a0ab960a299cf182cdc2d23d2021428749d759a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d91c6034ec56b870c93670683bc1575a16d98285"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4c84ee833b4bb52e5dff05720f25315331c9f8809cb46ec399034da4cd34ce7e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "6b44c8782ae93cd31ef8f589055d2001102bb3f9"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9cadc19523c1e5e46a4942fc2a7edd2912acbfeed917bdfe2474c45155d98c13"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c78c275d0836fb8c1cfc8f8e7b558dcfe5c4827"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "eb7dc04c35635c1dde33f399b54c786a6739cf7438da012538299e8a9910d5c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aaedf78ba83ffed091c93c6567bbe11b6f79314d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5de24a40f435461c779d1c267ea7b7eebce6a2e9ed316da771ba76435c84d30f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "416a7f8c52f6efb33109f798536fa2db844578c1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bd6186cc1c65146875758628a896dac31f019e07f385b8aa788aff7163653f54"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b3ec7a685ab651a61933c5508558dc8e4f0e324"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a136913a5470406206a1a986d43ad172d0670bdd2522d492df504f9f4204b09b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "7f5369425764a42f315105f25aa9a2131eca822f"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "94dd7872b83b692e79a4e006a5e727f23f4b1314e4afb96496d63cf463c3d407"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99ec16889c0e66d48438dbfd0db88b120f081a28"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "849e9da75f214d857456fc75be9080e9e3c2bd0e265d13356b6da54af2a1343a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e839cc538b51d6bedb4f25f47fe7c7caf80f22"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "843334f14138953a42f6196e84242017c92fc6d168c81b648711fce6fabae9fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+3/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
