[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "295c31b87b1a6f23101f97f31abb580547b3a925"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "cdbc299b1f372df1905a617153047921077d945c97de2011f0edeaf3e6f3ff88"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "549dde50c718872c152e7e1d4f82aeee3e83dc61"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a172c478c179da185901d1f94f0c7500178b5854c0d82b556d484b9e3dcecf94"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5932f8a7f9e270cec8a7d12654060405377ec42"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2b1c15f5d76cfda7df92948f2859644077b5d1933c953aeb05cf3e2ba75e3012"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a4ac9a84222aa5fd0d6cfbea03ca190ebec6f49"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dc21584ac0089692c9b421904ba48eafc704f037b872bf9def2d78611487dfd5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f343a8cb1554f25ba9ac57285bfb8f947e0b88dd"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "55e69070633fb626665a2e0942466076c8bd6406da1608ce8574b2b0a6e75fca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42ca7027f47535086284bef8ee3951c3a58c6196"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d6b9ac33876af55260ba3fc3b3c3ed3d565fb46edda5e8e0fdddf32ec27654e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3eea25e0ecde5eb3e5ff96d0566f77c8f67980d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "db9ca44c207405d2939915df4fc80be3cc03b439a7b68e975b1c0227fb7d4f1a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfb66052bcaa1cfae00d30396c50697f1e651520"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "77da7a79cecd4d33ea1db7312f7034bcc4f81632d330588acea46e808ed0f8a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0baea2752268af023bca714243fb69723695f75"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ec8fd597607474364fdb7a3815ca51712b4fc415ed353ea6e682fe67d35a761f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4da050977b95d16c716692bbe1f7abe856994f4a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "82d4ab8efee009607bdcbe0430d7624a0e8d1cde378e8380749b119aa1661fee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59789e544b72d9ff918487530e7a0dbe0257c174"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "161a775664faef0960b390c07d74cdd066812dbc5390077f2b05aa832b02f207"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cbda9d43d50e003a6adfdd1588a0882666fe119"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "27e112e5dd4f6989bedd5b9e8d6fcaa2caea87782606dbdcc40f43a1df33c35c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a6cc3d80a14450a2d6b392290925a627f6e1370"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "68644321bfe91f33bb598eb52f5893e3b6da4524ab79f380b55d143a8acb2d11"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "239bac1b8b5185bf10bc1599d3d2534b18c6f39d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "060b863f079299d5e397d4d40b7a18fa13b7542a3e0a30165a0329a4f13bccb0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b8ef1e832b4d9b0b04f4949a853a5d2bedb7e90"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3a67be2fcb5b6be1672fa5738c7bb664285201412de58454fb32c6cb48b3d40c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19d8a33ce5a82101336b814397dc30941554a911"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a5e4e766183aad0de0dd819400b9ddfe739e667a019fe2a40bb27a989c7d1836"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b660c385e3e6961d7cd999673150acd8e63fb32"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "81c5c974895373bafdb432e814b32736840c18a6705e3d2f2c505fd2d4eaa530"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef3a0a5cd8ff32c78211dae38ad5039b92fa4ee1"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d468037972b09e8fcfb25e117b576fbfae553e718018a319745cdb51a347732c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a56de8c3bca8678fcec0e1fe66a72878fb674a2c"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "3aa88d242e1efb24977ad6d0d6b1cce607101a14e1f9f1135a2566433f998209"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "466996f16531f4d45b6edd66217c07c8ec4b1311"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7979af678c234d2beca57c8505e3a34e84cd6ff96701e0ee01b664a08e05a77d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "272130953f2d50f07a50918d9b79be9b7a4ea0e1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b937ea9a21b2b21c4fbb065b452e3ac9ac862e9cabbc7ce2e224745c02242cfa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "0572c26056ce7b531644e17c5c6482697d2a2fc0"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "e361a2ee7ff9d1d54c9adc03bae5014d94ac8d00b6d080b054c172b3638b019f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ed3b774da3c1287eeb0595bfc17b8e9d0b45bbc"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5b0d7fd79746cc0f8b469713a87e452e03e9c0db2e4d50245e8213ffaa4baa14"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1dc0a4edec30432e5b22f5cdac2bdb20b92f9b7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3466febe000e7f1e7f208c8ec401dcb4deab27c2ce1c45ba5c2681bb5b3a06c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77f60249f932e4d8a0edfb0ebb32b1c834367b50"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ead44918c2db3208cb181427b4940142f2feb2c82253e2ca18c3cfb16fdb0143"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d394f0726cd39c8ad283c77d1f20602737c0bbd"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1fb2ccdd7eef2d9363303317eebfb241de051e84223e1c87c9b3b276548be765"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "74b38710d4a5537f50dff56546c128e0110250ad"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "99bb42aaa408efbe6d60554ed88488a5595c8153f3548ac92f54a0f630b59f61"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fd0fc2e5d871c7899b7560f3aed2e7dcbdf9b3b"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d5b06a8a4701505a1deacd17dad6f211c45f481caea42579a69cc352f961523a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a47101cb155177d34d7a695a7187f162d7fa6115"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "fefe496fbe57b5f439102bc37cf99b51669e7540ecb194bbbcfb8b1cb6719d21"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+3/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
