[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba36eacc5210b0393a6a5a09cf5c7eb82f1b054"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "be916170bb2eb3139e5199fbc4c2538c12b42b0653de92037a86c3d7ccc195f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac90e5cd7db6c56f2ddbfcb5529153397ed4e1d1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9dbee2b71f3018f7d219f5fa80c1bd363d8a8f9a719bd5f6a38d378f22e3a969"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c60470b176bb95f66f4fe2952b741d540e03d8a8"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "f840343d7e6cd51156620155d054717d96475f8bca117e1fa571623adfdc6cd5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5a8639c70e057a7434f2700130188d034a70494"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "e59eb0804fdfae1a97525d77016586020b2dc894a4dac218a02949872cab5bf0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37941527fa599079d3d48eb66acfebf8004624ec"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "785142d3d6f064f58a86125ebb380704cb0383cbb8cbea00c51239c924586a49"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0516322e0b1f930f7886f8b7b0abb4aa3ae69fca"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d6ebe47b10001821e3f567e9564e1f30f133d67b04e7c10c60486cdd79133e9c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05f5a89353f545b18ad5b77410f74b60b9477649"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "b663ab99b0812fc5e8dbe2c19dd0bb5724a120490138cdddc8d25d13b1b23dec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "530c4ef024d4cac22ffb2728bb4fbbd90217c756"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3b2546713f780344242dbbe5697093905bc8b8286893298890ad07fe39d0b7cd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f20b31fa409ae68984dc9782d1bf168daa59c956"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "322262b14c81c3548a7a4a2792251916e9176ecc97af1a895863a2bbba02b4ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "582090e2bda54d2c3611fb12ee44802f59bba9b1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e1e6dbcc2f11eb42566e8d50e8bced8c618802c14684ee40bfba7c8d44e2354f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3468a19c6cd211d06dd203aee58d93d1d2947ee"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dfb06f4a647d4f491018b54c512befa92a69168a1f028fa03aeea737ede297b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "085be252b5868fdca2710aa33e672688f7092199"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e0ed18c3745f6e5ba1c7029ba83adc7db6b4c6ff116cd29addb755990865a03d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b025e7a8c31fe7285d4bcf6f7f46c7f04df0759"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "876f057715b651a9bbc0f9751540166d3288ce9ec3056ec5f0f0efb9263aea8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a3150bb6e021b9553644e7d5f8086a28e7ff7e4"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f7488051617c956cd31f782c4ab4898af2b28890d165ebf65a6837537c22f9e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5afc517b6b057145765be3b581fd21f879da663"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6782478b3df0252d2eda18c99d0a1723b6b4fc1e1fc3efe8822583f07cb6c44f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bec6b8618e75df80a7eaf5dd3f134d02b5f4ff1"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "5359c0e33be69625ce6f63f889a9ffdb95d24c7e0d49ee64005578aed27008ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa1a6b64f9e6d13ffe01686de70e8f42f828f573"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "4b54d310643910df1ed3a621fbe3cafc14c9789dae25e4940223f4af9f5ef3a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a86f23e84872fdc482c42c8376ae4ef3dbb47ee5"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3db09182f1ee6c4d133684a66aff136c4c8c225b0e73f889794b876bb58c49a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fe556f06800f0af6ed6dde87254437f1830777a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "29706fe543120c56c69156f4abf6c866c4b99313493ff5e57b308c8c630142d7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f00f48019c4df1cc964bcafb830bb7e4bb896693"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d200e8ac7faf077fd505048d33a704c726066b46e3721e7d0be0ed79850aa82a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f900648f8434b6cd8065fc41a7e01f182bd527c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "626dca4a8d29ffeb3665e28946b272d4ffc9860c803dab5e70d65fb04e1cbfee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed75d8a5cd5953b89a2a7dee81ab10adc2af7a78"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3f56f00c64c88f80f98afba19ca22f0d792ed52866b5232d8f43baf8979d51b9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1057381039a6d62064a5f21fcadbcb500b63526e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "edbb1a7255957c3214cde75fd2dd97c68d9047d2e3a907e86132030c59ce1863"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e132c39dfefd675816f5dd2d481f339252aaf27"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "00bd5a4b3ce232e5c00b859f88a02dfc10e2d6611bf74c4900d73c6522dba373"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac5426d073ab5d7efde943325719419a7c6995e2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "44ef98f5386d1038a22f8527d4f9d7ee6c29c0fd034f1c5e8875da3eec2a76a0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc423d9c52c774fb30fdbe03711e22ffdc1b569a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "db659d8cb3dc71fa9c5f4e574dd486b8332dc970bab1a2d9b6776eda0330700d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v9.0.1+0/LLVM_assert.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
