[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "565ce20de646034aba82e57b447a0880e8dc9dd3"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "d31ff356e74d30d4c9e1bfaf3ca41053f6d16bd10b53e1edfe6e9d287b28f4f3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3cc0dfd409917331e87ab211c0a560df1126dac"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0d8964ec2d752c54883f3461b7df1b2175ce07b327560c652a08ecf10ce29025"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54aa62a363335d2f2e9d51ea3941c38c15f18e7b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "87220743f6a1774942618bea15b09c10f64441625207c36cb8813539625a6fd3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f65dcef89108bf278c6cb4eeb02295fbfb0cfdbc"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "71a233d9ea191e3115668c1b9c7cd3399da5c008f7fd6c3e5bf70008bf66a107"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67c3e1cf38b00567af858ce3bd73cff0ec5aff20"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6466839d346972bcc6cea2177d5bcc9b9382f69fba50cf5488e8e489297668ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e854e2c051ada8db011298cf72bcaa40fd283f0b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "864d7085a5885ffd2a526dfb69d7a4a2445ce8f688901bb64f078cb88598e918"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dcd915d8ba1f2e0e53812ad97ff6ec3aabb2389"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "635b755d5266176ff1bdb1525a9c80d958a079ea91d4d659bfe2248555f34baf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8316498fd03db8c6db6410ba3d6dc32fc61f2b84"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "02878ffad0b720015708cc9af9456da75a632b81fead987edb4a2f4075b8b0ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a54467231cbd362fb8b7600a1ce8c0397cf5042a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "390224e50eb1516552ce27e28bf08e14a402e565cd0caf73883aff3ef1fa4085"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6595f9f4c41d85ac44acd68d78969a795de693d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a6fe333cffa06e550ddef4e94959d34aa0696b022e8766e3a5db4a55e6d146fa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4d0165c34a0af4985162e36c2b904aca09b2e23"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7e0fe24ac4233bf770a4f79c68e567b0d8f60dcca9f61e72cb1e4b2342a96592"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a690731d989b8fc3b09cea1623a78334acc4e83"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "553f4ec0256153d2873bf3973cf7c4303e5cbf8cd0c5affe939eb1b4f2777343"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e0e3cf76dca4beb07de12e83ed08d8a12cb1901"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fbdf452970b1f8c2b77f759c53b50a269e445b87d78b08808e6c7d553154a11f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cda6df0688d929187cc3ed072a9167785204a7c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "df2732ad2117a7280d7dfc55cbe7c5f7aca6333fb4cc37d88edb430b546390dc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "040fa40783e2ff08c82f84803f9944ccddd0aed7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e36a0647ae29861323d54aa098dd28852230d695fe454706d5b1c7460d260b25"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43038b882bcf879be6da960d2606cf8792b2492d"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "486521e93c5ffa21843ca282cc7205511a4dab6e95bc00e80ac4aeefc330d7ef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f131e775440b7c85c8cad5b5a5ab5f6a180846dd"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0d874f11029e80148597fc7989cff7294ead269169ab98ba154582aef0e3db8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed094d75cf166e246cb1563492399fa12bf6cea2"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "b005341db9dab7a62f77b5b35af1c80d67360dba0662413f0c502055fdf79b9b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "653fc00b89b803bee0f6bb4c802ff7b0ef6c8edf"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "0b2e31f0ddd39cd9a168a7cec3cac0a03325a494eefb30cd37eb8f117af368c6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38ad14cc3e4f811cbe4d32d5ca0700b57ff3ea3d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7cd2628a4631b23d81b6186ec628f9e009c1a2df7e2a3773efccca3b224adeb1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5f12141798d9b0d600809752b53f89fd337918e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "589f95e7890e2789d7b98fe449289c5077285b0f200037e513163f8b2b5e01f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "d7675824b6b78e241b76518a425c8152a9edbe11"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "def5b8c730c31001320bba825101fbf2560f1867aeae1c22a247f947dc8cb70b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "856434e56d988a1e12a6c6cc8c43cf3a50c57219"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d5d5de2be8dcf5467a8507c64b418d3d95476ed46b0158d514cd021113f01f81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ba5253ebd3acc33489cd92731439baff5317b0e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fc4a5114240faa65c55e80a6300cfa891c9badbb685180cef9de19abd7d74a88"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc330b8e6901dfc5b2f1073afee04ed686e3ba85"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "46da27c0b88aa4a3562893205f2634b1d629a85017ff53299a1917694c3f6d81"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f1e7ec84d9eecf296f09aa94bd0c6bb41e45a24"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8161f8ac366e89e9e55d80f56a348002be32a6f3aa17e4d1294519ba585c9f5a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "ab353101fad8bc971e8bfa21dafdc4984dc679e9"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "4a9948a210c3c333325a5547434fa12a98df2d285cadc20c96b7c2d3fcdf7c64"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69667182e3c75c3d39a9cdb65b2ed816a52ad5ca"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "af8f819500691cd37b1d230e8d149fb9b2a5057b10c652401fd809edffaa3832"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e01ce56c443e9199f291a927eda5a96c4b41cc03"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "5c83501544bdf72ab20eb6630b76e70c7a01dac53e469971a25ed88f12b2720e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+1/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
