[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "0ee9fb5bbcc12b7c1a4540c9c2e3ee8e0a6f983c"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "873707772b9d610f62dd7d489beb25c961daf9eccbd791d6057ae1f4c88e31d5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07011268a8ed22570964929bfc370d4e27dc16d8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5f199193efb087c3ec4fc83595d8c45895e3bfdac7ae32ac9dc2314e17de724b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae3fb15d2980aaf136d41b85f7fcd9a94c52820a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8f56af1f28bece8d05d4aea52f1877bd3caadac23cf63f82cc3127c783facee8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c14d114e0bdac875fb3e7f33d3ade785d724ddb8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a7141e0b9f383b3e85b33f6616ecc27bb590f1e23ea468fa27de06d0c7f85603"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e428f177bf9bb47dab9b02322e0fc705bdc1bcdb"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "69cecab51ada9402ad0f751075fa5a2c980a8e21769fd23f5efaebe55d02caa0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1e556b77558b8cd9117c5e09338d8c8efcb2b6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ec5024c25667f7d881b29fd539df900a64448f549d81f0b72c04ea18f748dcde"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85edeeea54e8ff700fc45fbad9174f7bc047a8b0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ab821f69f23192b65c10321670522cdfa1529812544b909f242976a8c57514cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f7a9a8df8cbfa084ee163c075e42710b94a353a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3adf352c2a997678a58af130905bc3b8bf7df25de55d084b11fb84fdeec0f856"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "317f72003ebcbe1caa6d9a78cf630e99abfc80e3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "53afad02b8b446d49b3e5fc99d46e2c97c73adb3c82a86b482b0342e0e1c0500"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "758a0a4e9ba1f970690846f9fc8e2db95fc794f2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "08abf6f53ec84a0740dbe1ea862df49d52a860cdfb8d995c97bb5858981d75b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "007875bbe169d0b3020fddead26ea01e0e03c11f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b1960b3516399d1a76797c2a3c1ecbeb95b7c8abfb24444e0984b703f31ed601"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b78c111ba6bea389b61746e828dad68e1e0a2fd2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0d9528d4b1064a3f3cb54e1afd1bb4b04e3df2df93cd989684dd26893018b973"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82c5ab61bf0e5ad156d561d479d047c41a313451"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "335cc5ffead713d45c68d72dd0d1183cee177215e259d56a992781c2980d625d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e374c54863a8efc05e24c030f272c4ba972d124"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c56eb3ca7111a5c7227150fda9b1d6399a7b248a0b24f343e39dab43dd813548"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03f97bd7ec87ae8ca3327f4ada5c59d9c6f29d25"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cf47c49fd414a2c9c97cf1134d5c72004750507c833352e10f5206e1656d474c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3aae2f7904b7870c2a3064e7a03c955f111d0e65"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2e41664583646b143970bacd0363b6c1ed1246a4893825360a86b6f3dc25903b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b9a4b9c271d2f2714a642ff992c4e30063b636"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a2c971a0ed5bea38172433799bcb757266997c6a810fadb5991436190af851c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f5f5dc37128deedca6439024450f339b05bae5"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "5ed0f65dc46871f3a34bbc39d055a61ae900f2448ce55d0fd4ca1c5963e79bc2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6af20230705637c7db289f4c874e267e0ec05a3"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "128431ad859b489eb24a15c38f30a4568a728542f6676e2c2952779ba71ee5c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b58fe2164e89bbddd69dd17af5a55649d8c1a4f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c790de2032b3e4fb3c3bac0ed2aca697ff61c9e938cb872674dad922e8f99fb8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f26cc045f1d81e4de5c2f8c73262b9c2b5e887a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6d424ab3a117ffb16aa4fca74081258a2f43d45a0ef88ac564a147481b5e806d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "cdc3040f483865c31cf31ab76376a31f51198cdb"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "5faf8fa04884a557fc09b973a30c689c8207667ab0ec6cbd78ecfcc7244028da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "093884151f97e1e5ec5c7dbf5a4f9cf01ed57dd0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3456709679bb0429d67d2201e8f035c32f5c7e15775b50bd0eddfcf8e68c458d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3134d59d6f2913eb614e80a35923ed821926cfdb"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c26297dac2ac57cb524bde73a9eadabd32b49539de0d965bf63a8ab85f8d219e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a2b37da1e376ac13c8001a72525756c83d3c00"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0ad50cc24f6e770b981d4074401ee0cffb6b490be3d9e7d22bc3562cb7fcb1b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ea43b9b5fa042481d207c652b6c5f960f888ee"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "033aa4e0efe4f81a0c9fc02165f14176467a97e4659085d89f908214e6082335"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "0dfe2eb2ffed9e95f28648b2de49654c5ffb4ea4"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "b31fbd029c2ca36aa107c0343370407f0467a0eeda4a63c8e600bd3361015cd4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "364cb2cf1185d99311943f71c643eef607785356"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "f2b6ee0cadbdd4d8e1012024d4e84125b225bc6e16443a01e84ed22aa27980f0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31905b016d91f7e615b65b19841158fc9ed5b67d"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "fcb900dd15c528772c8575593dfa9a29d727b460a3dd50f3efd514e1f50670bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
