[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "ede96b81af7dfc06211811d6e85b6f3ddf022119"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "b16b46c10239e07f933e18598785d6dd98735841c8696924bc794adb879367a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "468ba1bbb008a41dc6294f9e3827eacce9520e87"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "53ce745210d5fa176fff4648e9948b3b94410fb754a4c288d108cab291cee088"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9db3deba08b9cc4e8402aab34c93208725fdb7ca"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "adfb06aa258a47e343d1f16cbd79fa85b557f8a2183f877c2ed97c1b9daf9e3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d090f9fe0635ed531e9029b6f278aa7831437fec"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0b0bee8c3ffc105fdecd22bbe23c2a91e1128942089707962612bd5f1121a54e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408c970575304f81a519d85025d14e4a234ed87f"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fd5798b86594bfa42d983f03b5f50bacd215305e81c456093a2f1f0dc6e7fe2c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfbdc316ec4cec1dae068c83af3e88c874d41547"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3fae1794f07ef099d7742eea0f76e27fa73e20ab79671de92d867019191143e3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce753c7279d6e5e3cce2412fed2125c498b6c8cf"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9e8fe44b1b15b31a6b56a3bf7a120eff25e52698904f19f8613bc7fc931ea61e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "255503b1187a4f45b05e6652bc36caac3b69517f"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e808bece0638657f084f347f8e2561c8c4ff7725aef54101333d49847c5e03a3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "284ef71826412588b0527dbf830efd89f601fdd2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a33b5eb2245c9fb05967d46d4f4e6eb5d2169ed0ba03608fa92c5689d80765e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c6e3fbf2426f1cbc53c84aa0911d1daa5ddb867"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b8029bc21300d85d75b73e989d2079f29a600d096c07de4547a416adf9ce3b82"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "074d2cd7dbd4466579ef3d605acbad3542f22971"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9ec979a11bce639c0b4cd6de6713e3dd7eef6b1cfa703b6c6a938e2255b9983d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f733e2785ebdfb67a4407d68005c8fd5ed5dc2a2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2330fa00cbe5c1da6174c4f189c8616857e5423635a8671a039a83fe2804515c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01e359b1b2152238c810665334c2e76e8d77ff1e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "137af8be2d388ee08c8feb4f46304708f9233a0d6880d698dd432ddc41fc1cc7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9742aecd29522f900ac155ccf0986419bc0fb2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "76c8ad0dfe9e1bd0e7bf772559e3d5ad4d868a70c9f3ce8786098ca62964adf2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f21f46c105c31418d94e48a1f9f35716064f6446"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "90f0862be70c85da1fb59a19cab8ae19939fe9b3f970ebcbc981a991e2f55d4a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df3573430af8800396a42c9c0a4d1c3d7753b788"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b201506803d6c229f203ba5541b899a46f7cd57514a35a3a1861a5614808ca3b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf82b1b6296e790b8ed43b507669dfb5e6207655"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "61c681c3fd8a78bc7abaf59763b37c1ee6c7199829be09e3d39ffbf943d70e95"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e91309f4137ba39e37c792aa363fd0d9ed9ea68d"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "8fe32b186b06b4859032788f8e4981bc0fe8b793697652845908b98b048bc256"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff47bfa5c154a0dd3b55935ad0c81eaaa110d537"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "906197d9a37157657eddfaa6d626992f67e424c451afc7988e8334479af99b44"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5074c9e171a506de141e15aff5b67ceb3e2b6ef2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "71fbec55672cde3afb08e902f968f2e72ae715c50c74734ad4fab63e7d57175e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85b3484335a573e35c09a447819127b330ef1291"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a0a9fe52d5923b846fe22c593058c7a6e4177939cd8831fd37f9417749a59fe1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "bd376c4b0163b16e5d263a80d15264613089964e"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "12b2af6a2c3ce9167ab92743867ad24b7ab32598d272d427d2a862bb82a064b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96d3aa591a02957e674aca98c9963af801a9bdef"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "147a3aec86d02189bcf6164990c975be96e55a9a3fb045dae3d5181b0aa8d250"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29f92f5e7f00535f6a87f8c45bf6706aa783db3b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8d88bc1317c72f3c4bffe54892c95ec584122e817abc32b71d1889a183dad0d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d90cb47611fdaca6e24d2cd88bf4311389abcdd4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3d2ab125c5e7657fc3a5ee33c60309756b0769a19926f3f77dacfd5a3c7ac40c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aee08fd6b1cceb1754dcfd2fe6ac03b40ebc7029"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "321ddf6b655e2036a6649d37f2a9248356595aa6e5da22b19fa5d570def62c4b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "0a4de8e296b64e01a681d673489ae8d4a865db09"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "245352400061820cc84c34a9661ce10f87b7cee206899cd3b43670c6bcadf945"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba75c3ede7329ef07412d8624f438c20aac3290c"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "c54b59a7ff587dc919bb9b4c14ecf1b05a30ca4712082458d3584c4d5fff39e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c425c3d742f789f89dfe3b17e5012c312964f98"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "348eb74c2273a6e7cdcd32b248a8d0bbc30268d538f3ff6e561905ff8b92bf73"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+1/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
