[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87b9010b56ed7103207fe9237a146f63dbb3fa53"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e0b2106e27ed5d422ddcce33e8223c0e7557c324bd9472ccbe3bf4400b4f2973"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03ccb8bba40a45349057830a4fb0e28fb47f4996"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2a55ceda60b248c14ac6eb63ee1b2e71595c8a751b20606fa8152a03076c18d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ff5ca0f2e011c9582398a026983c4344a0f493e"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "ef6cc1b9de7463bcc052707f00e5b6fe175eef4edca1b4a7d7c3f43d7883b153"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce11d3396814b36834829c4e5a6e8de26be63e64"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "acf15a28d56558a8e923be1adf5dd68949c49d1bf9b6d06befce689d89a08f5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "259a0450711b9252057cd4e52476d4da15b3dcd1"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "b16a6de1cfefaab3f42146967b8bdc0d982a53d7d558c2a1fa1e19ca1c611ca9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a8a2a20b45992a04019fc6c489db40e77af491a"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "6ff1570cffac702edc0e5f3ebb1790a9c3ccfc4ec3e192e74c41705580eff8a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7dc46d61225d5b86b6386fb6548ee6566bbe264"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "e5fb1ca403a35fe5a0303369aec17ff9455e9d0c0cf30e09875616dece9ad326"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc0d63fa0ecf9b0e1a3de0c5be5dd532a68d4971"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "06185d44f5f3a40b67ae6698f60bdd6e112a07685bf90781448b06bd0cc2a6bc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9ce0d986b6659a4ba1371cf4644701e7b0db701"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8358529f354920a3035189a3cc873e53d6d698a774407d1d7742f435ed232d27"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5549071c904899c5520f90951f3eea4adb3fa89"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "94f37d2e9d7f48254c47f32896b476c757520ca8d130eb136afd5c9a29b429fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f09707e55ad3707d20820a781cf04137935508b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a54c0dcf9851b9c8320db2c194aa4646364364af8cf2a5a96463b56408783b90"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bfc903d51bc02b7fcf251f698aa712c40346bde"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2a89f27a7be6a4fa9e5506c4a4dc5ecf4175cb61eb6384d2d9c888e232b61947"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e84dfde5cbe309a9099dbde3fef72ace08f46b50"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "eb33fcf92d1d0e4d45bcee694b8b88584157cab85ef4a79ec25982dcd2055825"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc768f120b85556d7b1ca29af76ecd41f8f6a181"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "03bd2bc4a77c65ede972da54631fbef58f00567e7fa6f2d8d6aa462de34f011f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36b7adcbdae6c1e68c2b80a7b9971adad39f38b9"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d84922b5e23688830a6e78174e6456ad79fe84eaf893cc2f9603826d4c21466c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1033e7d62c681594eafe0dd9da882e2df197ca7c"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "4ceb5755f687c6cac6b73bce2fb5aea6e134af3c146f63410bf9861bf3a8c585"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80825f28182725636f8ac8caff5dd87b844a825f"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "292b05f4888cc42b42f71e32c4a712b5eb39e117b79a2ef6c8c3bfc1ef8ab466"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6988cd170e597ee32f3fa60e01efbe352833024c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "511984c91fcad32aaa5a0a9bfa12321c514d03b61a05b31a64e11942cea6feb2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c02dac8645ecf3ee94caf38e6cea092bc426cd0b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1ec8a40704ec732863d0952dc83df8637678f4e4966ee89563dd7deaf97434eb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ad3f330816be173cb6e77178122c5a3f0bb0853"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d75b3ba87be1247af453d221a76c4b8073d9beae9946e358b6c047d411e22482"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f38356903fccc37718c1b11ced842859f9137c1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "50dbb86f4491762275fbbbe2675c39192ec6623809c0d6c14395ca3070d13fbb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f51720436afb5c19e464a6edcc01ce7b2b03bb99"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "81b78d0225b288ca48923942b3a9b505cecdd9c9be28da91a658d307aa685313"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81dc2e1c8be645208f7a5f7116b9a4a4120a592e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a9b27e9459e6e5bd7d07398a7b94ff15919e4e622230848482835339df10beae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "598e8e2d8e846b1539bb99bfcaf4c8254ca24ecd"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "3917a576b2bb4f87c35e10ae901f0df3051a9e784669d9f9b6f5bcb1ba4f6a0e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e17fdd9be4790de03c3d0c7b2e11d1ee78a05416"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4071fd0e0e7d5a4fd92bd92a57f6b53bfd627bfc0d46fbc56f3dd09bbf438786"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dfbe0f582edb6e8b9602a86871cb2def28dc4c6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "efa2c384efdc73e427c8b2437c95d1d9ad9a01ad423b6549eef170d883f469bd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v8.0.1+0/LLVM_assert.v8.0.1.x86_64-linux-gnu-cxx03.tar.gz"
