[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "da572252ce16c44cb5a984d7d7fbaa4ed6b68d89"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "48242858ce66d62f1a35578d4ff3d4e0c7898d0623530e8ee5d8bf162d41c25f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad1e98cf293122ad98596945afa5a16c17a556ee"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dfe974351d5514649957b08ef63b7ce4d37c6bccd0264c4dcf25f6ec8f24c4b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c67c8e41831890cf4a3a3e6d9b44ff7f591001"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "33625aeb8d9c9286893558e51fd864da0c4dbc5f174070748745e6b216acef9d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d645ff833197eb9b741d7634cfc257ebf460ac98"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1c7c32d8e8ef18aad82ddc9bb1d77812c5ec26bc9a0ad69e94aad76f35723253"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f118fb5010bfd5b9225513d5067f59ea738aa070"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ec3a59bdc28ab6ac159b044a7a4d0c89f0fd8c85592209aafdeb38f633536281"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a70db2561e15261cef84d8b5f2cdb9ad7c6effc9"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1d0af18e6e688e79b2abda5375d499e50787c2e9ca2079f01a985bc2904ee150"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cb4032121fb857eb457683871a00582dcf9b86"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9c08fd13c7480d6aa15d904d818b559dbee635995ad3756b2426987563108799"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "203fa34920ac401387280503797616a05e00fe3b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e79e28107f2459b08c3f575806ee23c542e875d0e3fd43f18efe5e287cd9d1df"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3941ba5f52f2486621e48b97eb940eb82a5a4365"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "defb43101a52883615c4480b791155a9d374f4e288040f3ce83ce9f9e556f8b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e25f54c612363e6faba2420df70f05681afe81bf"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1cdb9af5bb6dff964d2318b688bd3f8a497efcdf6bc8c5712ed3c7ae44a97264"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8018fb8533c4c4ee0982355f6e0c767ddb621c2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "966c9e4cbc9d155da89b5516af103b483a51bddcc330dc2580e0c8b8457c4626"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ba3baac87683618689482a102f19e8f95fc186e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d59d7fe3fd7c8598a36729b25ed250258adeae900ef272664a587bed2d5f8e6b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aef98f8dafdf4e063e878b692dd24926fcf00ea"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "840bdd1ad4252b6107a5f84ce1d8268d4ae3a5de62eeb5f9e08818b1913341bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42c046cd9f15a6a01fd349821e33a048e4d9aaf8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3428910dab2c4bfb5d6dde28c24b0b007237deda052ff84658b680b2848405c1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3261f38cfbbd18fb2d0c03bb7f723cb84eac5dfd"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a8a8a113a7b0b5fbcc2e4304d8ac5985ea15f593af90c6105234021c73ce23ae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f182aebe508fc435975215e6fc59545de2108cf"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "10cef2b7738e2a2cee3b9a2c0daa7fb677f1ba55e5154bb54b43da37a41a3d8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60d055517b5f8f4251c32c65d83e90d8d0e8cd46"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9593a59df3effaeaad426d4d6493dc11dacdc3426a3ad1c7133ddca8dd94f7a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "212cb7d8e9cc4b68d09f07de2a11965daab07f48"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "9ae13fbf9b03630cfd77140eabd63e6436ce99ba85823b409b03f3ef3794907b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3124bb8825ec2c990b16d321d074647b2d6fb659"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "2181c14aae9f76c190eb614adc30829b02f021578c7c63d19df423edfc374f16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dc2e7518d7dca2013279613173577ed9e7fe333"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c9d15f3eeb085dbaab3def2082d9ffe46a65165367148728edcae0397afcdf57"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5403d8f35e175a179f996877f46d098409b9297e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "feb919bcc542f12d34e425bf96fe33509c81250a08ea9844a6aaf6abfbf29a9e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "ba10e3881046cbd3c21af21fd669aea5e011d5fe"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "ccf61e275cdf4ffde09b2cfb9bc4938c0b4d99317ce6963aeb7e570db54364d9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a54737c527ebcbbc2fc8c07316306f3a6774ef7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "39fffdb3200a39c73ea5a045950b8ea182e9cd50997591c34c963bec8b116f45"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5683c31952a88701516d1009c6b79292f547d24"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5e2813f15e3e54f89f97a6afe9112cfc02823ca8df9c0e336c1b2c358c939a68"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b17bebefb9b7d4f5fef433e1000fb8eafc89150"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dc563a5b42a1310df4bb83599413da09c8c509e4e4f51bd0f7904b403c776ed8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70caece1a2e9c3dcd98dcb01c4de885b169e469a"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "63f197d7739c037f91a2db4cb782988f08956755784ffc7f6335648d0d965c52"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "eb1671a5b73ce74c04b1363049a1cd7e3881c235"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "0410a70732ba6da85a44a7d21c4cda1ee4b4c630c48e40557da81a7de7573dd7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e96c59312df059e5d69d7a97f22ddae42b206ba6"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d506eee53e74490d7332f4f4cd335cbfe608ed97c2c5e4fc91d3685452c5da4a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb795a5ee5d48173013f015035b504950010e454"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "8ad51d4308b187a683a051176ecadd273d688773efb19e3e888e8535e323d52b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v11.0.1+0/LLVM_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
