[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "93e0caf6f2ac2ee37c576005b9ef84e67bc13c85"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "6d9e952fdd0f6042dd8a14dfebae13452389d9f0c9d302056de296f1ea7874b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3644c86fbb07adf8624bb01b28a351a4a541191"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "52949e08807f8a0a448818cb12725e716184ef7e1787470d79542a4bd449a0b8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e6e48d832009ef07a92b4645ad8e8c6875aa91"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f57ddaf0b2d84add09da55a3879aaec70effb10e5271f02189dfc27a1dbe8214"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e307efe3ecef5cfcaa6db674d3dcdf0b4e1800f2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d6b09eae1207307757db63ee4c0957e93bbc0d59124de889842d0de095c8130f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a621ec07d28374329b5d483439b49a3191ab8777"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a31b90e84ac8118ba6e5a4d28570fbe83c6f1f3b07a377dfd55106f7d756c1a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07d627e8e1752204389b13f9bffc8506f168ac8c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ac44cac4b08052745363d0ca74c4a90ae2062eb0d875cf9b95904176430f28e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acd42067bc59b84ccc61da28451c608cff28b1b4"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1c4bfaf6f549249d381bbb114dd81cd1bdbf831a097a83c107301d1d0cb5da5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bc372e838a10218e99e0af899cbc8f82bee18ec"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6cd8643cb05115d014a71b3965d11884c8651e71d1f19ee6d31ea7a3ecc23ebc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77ab9825a86be80093d8232eb55ea00c2c50301b"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5bb833aedef6fd56bdd739ccfa7848fbfcb3274e458836b032e55bc511ca7f39"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80422d137fb9a048ab253bfed759b54c2e025442"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "102c80f90d3467a6becf5ba7a4a6c297769d6147d55cff9c0cf51eefe35c9db6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ef1db6bb3dfe0860a44561ba65dc4d06928f8de"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f8f60b7b96d391b22f769076fc85f74b1cbdec7ce3a107ec471c2c6b2a84dd6c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c91cb451fcbc5dea8fdf02c30038fa11bba37cd1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3231d3e9d275e5c516a196bcd8c46ad92c2eb751a09a55d64f1a148e8c70943c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e544e4dbeb07b759c090bb129a1fc93a3c78882c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d16098ad5816cf9e6636762c4f0521c93ba08583ad605d924639664941fbde09"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4f9520a40a35f7502f56023dc84087bc0c6a62d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b189ed1ad378a0eba46a113455b73a509cc3a7750d185d8af791977200514cbc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "084f4016c78eb4dde3fe4e36df53a176d069c1cd"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "05e1f4f6a537226998995b30939be7547d0ffecb0ae418aaef85b18c985312ab"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d51f212362d887c48d065a1c0feb5c6f53109e4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1a9a675dbefeee0591c1d510eb247dc5d2685c8567438c71bc314d7eda5257f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2300d9074338cbd2ad2d9a3cc0c66807f38255a8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "81de9cf56390263e82c610494482aad6f5aee3289ae3b06c770af97dcc0ffd10"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e0e684a916ecba0975e046464f2fa1967a59a47"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "13f11bae0be6ce956e99cf2893a1ff476c04e9db3435c4c7620471c54af13516"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89e92b39a323068cc5d5721be892b24640fafc58"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "e46bba9181cf09a30e2d4be421ae446a819f4db4510e48d5ef5033fc6daf77ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aabe1996832a3724870820577aa6a94647443ae6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "93766b4319ec47890fe166b7e9973e854eea81b40ad40e92a19ac04a590945f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49bbf3d28bcb4b72811ca7e74891a05736d34eb6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "366872a400d13982337e1ab34164e06daf52ff97ecc5b9d358198b94b0a48d4a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "e4e7ace3c02c6de8d87c8fb5ad815fdbff8eb9e6"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9a938c0cb4d96445949f3ca34fbee8e1864d0105fe29c80797141610c5f6c14a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9bbf912efcb20d9ddbe57f15948bb8866a309c1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ff68c5aa997a436cfe5d8a65519be3608d01f01c3ea4a7b7f1c0d982026bb83c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f36bdcb2c27ec7390a5d4e7f4da92beb3d3b14a8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b178b8045302d40017860c5d3c92090f22f0e6cc3045b9fbe63605b5fa7eae63"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20055f96cf01a12269cb589215d2fc74d97c305e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "573e2d44dcdb0b53aa16360d43c18e53886600dc929c7f73e778631919bac48a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1994fcaa7daffeea72e4fdab1819f77dbac39ff"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d14c41e7fb522a43c73352970f8406d9c9f6c31e8f26ec56105894bb49f0bd63"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "c8c6d2196f908fa2b39c2780dadae0b158231df5"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "e5ad69701ae2432630f1b23bc234da44a7630ef58e9563332b5654aa73525979"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7a1c25c13b81231a591dc7477e9698d6028ffbe"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "04a024671d76ae2c683b7a4969f69fe284e88ab71f05269a1c7277c89f1aedf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc1a4fa00574136a01e7a6d9e0ed759d87f48719"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "e8bba284c07b0798590ef5445f27969dd23455f45904b3fad494d2a8152f770b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+1/LLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
