[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "5c5bfaec9cadd9719c6798398136c12b59d5a643"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "98bed6c1cda8d4957e0e54dc3a377b3afbbaabe40d2b828fe2dfd78d3a0f614a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea996833f914528dcc53d611a252a25664926d61"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2952cd6e58ab2f6ebf042058059d68c6a63f04db22748f8e06907c0376f15574"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e4a5b9a4c3e7d9e9fdc9e82bc62f2ca9ea2f89f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e450d9e3c54f156aa8719829037fd314ad800492a0688c981ebe5ac96f9614f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa7e61c8692ecbec3ea0bcd7db241c73932f5ec1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dc34e20d4d58db1b7f50b9ae1ab0af25f186007fbe4e47054a0f0505c9025fd7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "203a08da0eca70963d56f5aaf24e6ff233422f86"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2706faed4002e80a9cacca0e081a8f87e14fe097ed4d706332163332413cbdc2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcb3c2084d2a2ccda5b9ddecd8208f54c8712d26"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cdacc6d0d39a6d60b66826328d132fec11724a9125b565aa99aedcdfac3b6542"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23127e588b44d5b4546e418f954f65bd9049162c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f12de270fbab9e92433c199c940459b54c252c30c5f4b4c2688963bb4ff2110b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2bb317ad6a7ef3602217bb2af9f3d2e873630b9"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "91d6235bf015d57900a1dfe6d732af70b5be7ac7bade03b7a35ace4ead055513"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5918501bf0175b6025d47c0f4ef0432835e4b353"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b884b1b94d3b644d429697f142b7ed9920e357db5ba7870f35706e18d5d33ff9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cafdaad984acc3d83f9dc85ddf5a09ac9846b365"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "4bb82b1b30fb5ad901a16e6f5123fe5adbe3e595873f9c8c45161bd5c051400f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c38c465b4fc083d53b19a43f829c85e2c8ddc797"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "db11bb90362c9e6ad91379261caa023ec86cc261dac146440446a087a140cf2e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea86f75b60b9a4aafae0ca8877f3d870a23f462e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "21222df75083cf621eb59adc8b33d9c35aa5e05661dd7790d7bd80151212131d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "254f776bb94abd1451e5fd55324b64acb5851031"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e2664f3b1968d2913127880c91a3d7ee9c6d766cf4c70e1b3ad7156c9cca2ece"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2608d1c137d77efc264cbf7e1f2262e38accb7b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bae1ec24c60c991350ab78296e178cb01b6f49161004dda8f115d82db4067ff8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a3cc12a2df00e1072afd12a4b760a120ea0658e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "41ecf92dd7e9ba2b66f4e1a0d3a0373743750935932df51ba410ac078c114fb6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c593a84fb227954024d9987be5702e6c2a616ae4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5215ed32b3d2cb1adb798e6387aa21cc4bcd7c74fe8385507a5b997f7c473616"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9913e8929f1938352c4835ac07d0614dea848ea3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3c665f121b5ecdb71629cc8a64e4946adff1e04742dc34ea0baa2a04a62f7244"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cc50a12913b5340680842395cd9208e97782a33"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "9c7c30bfb8f18f22c33b5e4dddd47eaf4fb7bee74927acbd42759e3e448881ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84ddada228d8dc6188d9c87fa3211c599b438ab2"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "4a9422c79e787f46e81875cb6cc5c1e51467f44237c2a91a8dc24663e9d5d344"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1830e58fc8e0aacf1a53ab19a968c8aa47009dfd"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "895b451816d84807a7cb6c74f44bf6cb9f2f84c13fc80b69c658f972e5615a8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc2b7a6b2c139df2ee447d9125b0e2699d706132"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "deacc1ed281c2be5a9f7cbd80ce023f28ff1a8f62e93dad53a42139c315e5aed"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "53b92fcbfadde4da3c697314794ec84c2fc67612"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "bb36006bbd5221f08fa22231b2fee9d06081e65d7b83d9cae639680fdfa03e5c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd07b9dddf2891e502c27e18b05c237893dd3810"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8a5d54134bcfc6d8310041c7090455960e237ab21b02b8f2d25f1bec829784ea"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db8080547b9adbf1d8eefb2eb8d8530e0343ed7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b41cecc1455bf1f96ea398fdc9570d74c7d7115186360b4012d08dcc97345e28"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cce41779ff37c7251198afc65bd43b68719af02"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bc00ad804f27cd8f0fe7c7a75f10952154916a4d660a5a54008133d8eccb1061"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74dbaffe76c5ba0bdeb3571be83f81cd82d3cb08"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c64836faa476217dbc9ee9518f985ef6c802325b7435ee5fff0485b858122eee"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "cf12c042659cffb09a390f3affbe4a409cb97fe6"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "4c215822ad1d882083fa37d909c3a8166c5fbd08dfba17b36383a6ee799a94d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21267406c30d76d8325dd16b78ea76ab9f875d26"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "bfe604eb651140417afdedeee7e6590f64815870944663433c1be0e707b97a0d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d268754e48025c409b96582da3b9045928dd14e5"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d469cc4e8131feb1629ab0b52a5ebcf96792c05a258214b488949d1386f6664f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+1/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
