[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "c27edcb74d4d4528c0a89429bc5e49febe98ff4b"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "a3458947058901e4772b1a9b2d9e908cb8f926671ba878e63cfe1148d0a0a1ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a5680a9169409d9e0ed67118eca1bb0e2cebf4d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9572c68a65de2a1f6a31345380d122d3fa1431e11c523138fc0da51ce7b8842d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dcbc8d8e32ef77dd3ff604e5f98d8f6dc401049"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7bb8508ed1b402c6ea1008fd6be7309c83b0eb72aa57756a20be3622011477fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "742c06ec2cb8f940d563144478fac4bb1daa2920"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b9064d5660642095e8744e2c5b4ddfabb524b10691a3bf473452512eae0aa05b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8ccf5ebb4a6c7c659cd97ebea541faa1971431e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5cdcc6570032ba45b4b4a48031b3baa99e1172d0a0ff67f3527ccf378d872416"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1444994b138ea28388d1b3ca6de1d9c84d847aae"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2f611b226e4f894a61de7ece9e8e02cca8bf2a85151184731149a5fb06109e35"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bda8db7ec9aa95e55e80e299b92bfe61234e418"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b69f0afc28dae3f8017b905f9b8cedd09f956052849b96119b7daa62f4317ed9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77bbaca1675979d12988f4106e2b535540021f1c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a5b6daed7d9a699e2a431f463754b0926cfe6dab703c780be54b81e6685905e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53cad9b39b19ce1294e9a0ef231c95a45f394597"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "991ab576982f2ae3a81e5f0495e9818980b7d82baa58974b0223a3cf89d27d92"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e379a2f39284052beeca86dec09999b69ded9a47"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a9e7192cd21c528b8784ec83c43cf4a646d8052ffad240e5098e85bec1685542"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7df2cbf992163f26111e65a404bd3f98253383d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "99ca9d58cbb7d90f921c57df217b86458cb073a61455d8a82255b62213969110"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4a433d0cbc72b10850b6e6cae86c933e4f26443"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cec0d7bd72abb34cb91064618f8860058d987272afe362a7757b035b62645e0b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef3e87ceccf2415b09631c9a6bfd4076f63b2fa7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "27b9f522512c57269923b2ce909662b47d9d1a14a1da141ba816ffda157cd99b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70b9d994fa63cf64dd4c0f1a4a0041bf620558ce"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "afa45d30d6fd838d598c06e754163f3506ec49102560724c898a38b2c21f2c02"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25f34e1ce6163f47614931c0b6d8a3e0a9533efe"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ace0c9640f918e43a63b85965d39c8927cd751c5ed57626d185ace6b20a8698f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58857fd6d27dcb6da1eb72154d33af73b3871b7d"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6d4eadba4d09fc7b235a64e2bb0c82f0a1a5f94237a9ba1f4b7842f67c1434fc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08860e2e81bf4d21dfceb72319b3feabfe6907b9"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "957cc73be976cda5c0861cf3766f814c6ed2602816a7cf0345005a558088db3e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fdf38b54dfe3aada78bf0d33d9dbc707cbb49f6"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "f29dbe2a6e08ea9ede3aa9f748c2c54cce52d42af04e4ee22e93f578140e1ab2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "823fb37f54abbee73d7e8fda6b7e1cd57935f962"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "f57d48c543898a1355cc6f941101222ebbcc05b2d042391146d57ccbc8e5b988"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d67dd31303bfd21062ad518d0209d82ecfb05353"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2a5295715e5c630af11a33c015fbc19e74c64d88a5aebfafb0991315f0dbeebf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "032491a34c80d1b584b69e02dc634e95cac34e19"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fea37084676d7f924ab05d0df336781168e5d70eb304794bfcb1370286c47dfa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "e497c86737acc3a101a4487c8a433db508fee8c0"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9a7ac07cb54cb3028bbc0bd253033f3bebce58c2a055d956c754fc949853e4d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bb48b075c87c68f3c0bfdbfb034cdfe4e13abc6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2cdd0967e6b876ecc8b3724f770f866d5741a22708805332c414341095c10a99"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d82b3e061f74069994539ec35a1bdf7cf6bd4733"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2005920660e6fd03e3121fde9b57a93e07111674415489917ccc576149453e6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c25442bc179603cd84a58076dcfa399ee45c085e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3dc49aee0b6a819d677d7bf51844e378f9ac81c860d368e054bd5596f75e8714"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfdd3024ab8bf7c5f2c68f0b31f1437f01c86195"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "152cbce597d7fe2af0397e8346f14d5173e2baabbed1617226916e374f43a7d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "4c11783964b13cae7cc7a1ec743bf61b0c068395"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "802e667b3f2856b87f2000930e717a307931b1b76b0388ba3159bd0f8a034caf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72cb2d87dbf4858796d4cf4ddb4f5888c070036f"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "1eb102522665100d7e8fe2d9eb77e698ad25d770b381bc7dc9bf920f1596bb0c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0a4edb482c52cff79bb445665564dcd75fbd8f2"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "ed24129ff28e4dc28667a901f214128cb119c82c917ee9ff8a1dfb330af04442"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+0/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
