[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "01264a150939b649f30fd2b8e266f71ab1921614"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "7e53cb06ae075690286c66162b5bc5639db64ced7ea98fb973c98770be01bbe0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c604effffb11b22ca4675f26a54ee3e502c5e0e6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "823058c5faebadad5aed8e3bb606d5ec7a5c33a7088c23ee2239ff5e847b5099"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b526c20e722f51bacc24210ae10252ebc0d80bf"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "30728614a3cf321fe5f86e8aba462c31981805b7b0a9eb5f83ca4c663431dea4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8554630ee4b5c0f8417b308161dd6a47580b7fb1"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ecf0c6930fd226091d431f2727de7f90c6059b754e7e84ab9bd87b16d4a112a1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "204e169131d43f3f215b5e3dee36553193eebc96"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1973d9277de87fba0d15f4b6e93d211509c6fe4608d6377528290985f386d062"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01e00f02c78c3e4cb7b4cc99820b328d32aae692"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cd02a880960f9f30bcfa8f0c4f6f2cbde53cc4db50c41a2fb4171bf745cd5df3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "162e9cb408b925bc8b1a1386db2d39e5696d615b"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1c7eccc81aeba2c7ef3ef09af6df273623c8c251fd20d16d31cf1041611f9aec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71c35a9ba68b9349146ea7edea0636ae45ad0090"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6466e7d046bf1c1375fdc3f0d82df67e45ab22a4a10ad1c50c322b6757fb9584"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3989de8bfdd7cff16d1d39ac3bfe4958f08fcf93"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ca4eb4f54fe60acf57bbfeb8d37ea982a1406f7d48b18ba742c866cffa0b1253"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8b9a4e02efd600e1328455bd9d998824d3c7c50"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5fa8e8ddd305c3bcc82fde81b93ecc4fe4cd833be4488fe65469ba07e00c2131"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "264f8ddd44012df353e76272737d19b3e303efe2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "87d8ef502145803563c49f09b79b458362db7c902ea723509dcd8ba9cee04fc1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "140e2c5d03f71a97a36f85836102c0dd7cb204b7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "775d4220645b76c7e9a7bffa243f3d13e59495917a80211ac92de14de80c9582"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7ac30d255a1d9e591e0736a369cb0658c673ffa"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bbba4264d5840bb7a1307989954b6f0fbc7d18f1d8931f7ea82b39268b8709bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bdb2085648e2c71c3e3d89463fa8482c0db43a6"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8dcbd5359d037b4c838694d9d7ea34d9b9492a9639f4ce6b702532d08e29d21c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61d22ff4aa772c6374977dc4cbf8a979df050b7d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "aef4d20ff19cde05d2cdebcaf6462e0d4c541c101fe9c72f38257be996d74ec5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cc7b2249141d73d7ef6fce33544522586786400"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "22a23ee4631b2117e70225c2a9a7d7775d2bfcea47d65333838e0cdbd1a5d9cf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd084c3bb51a77bc0cece048e2b143cc5a63b085"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "27d97cd44723007e1908c4b3399e99a864b18385a5d440ea00b4d5ab1e529766"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3545df9649b416efc5fb80f9485f87f329457019"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "813ba3b23653ab76f98b467e0386c467697da79ba7d042901da04510f5c996a6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "868e784208551a96c275e6478c8a919d8ee0c3ba"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "b49ea55d5f74f20911176c572223765b6af20833a112874f06294019461004c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd1a63b919f6aa35490e3c9b3993981d71d8bc1f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a93692b3cea6e08bb585147aee8708ccb1c645df982a47ba40d6fa30cb277f03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "683a80cd4223c2373d5c6e6e662b22bc36d95139"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d156b2a515631fbfb500d725e8c1d7c48148cef5f17c4a8e864854449b1049b7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "e85f1f645a2237e2634155ec694f06e737bc946c"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "85a05a2b86606e5c0b30da53034f70be40677afb6c4e3d74c634df483f2d4b8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "889219367c433a4fe96a481658a623166a38a05d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b7fee0f49a5f4e41420dcdd27373dc56ae0169f44f2525c3e52f011bf90de3a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b807a1254c23cb429b800be86ba596163868bda"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6f87f0414a785320cf478f7d20cab8957752c7629b421d0df248dedd016c0dfb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9cdcd2096a5aeeef7bd8cfedc0a7bd1ad07748d"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1cf4f03f0025f8e94f276ce18f5543a5ef049e8d087f206bf8cbaa9c4d53e742"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0043db134ab17c0977a8e4f5fa3f4957e4be481"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a6e5c0dee5f357abf1fa840d1c0879af7d44af5e718f8374fa9dd3f560fec159"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "10653b25d01d3be2bc8ff4851112197201b27543"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "debacf6d1ff66ad9cafcafc0d0c958e7fdfb9bef15979428b31cb6a15c346f4e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a36ba204c2d2ef3cb00a7e27c767702d45d309fb"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "9441b23bd7b7d278777ff2770ef262b9751be6ee11063e626d4a26b183fae408"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "368c337c2d5159822aaac7abace4a8af9f4fa6f3"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "cd8b40ccbd5ba4f9e0de17e8fb6cc67096b6b29270dd4bfda5917a84427df76d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.1+3/LLVM_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
