[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "c1f6d9e1c715f84a3a63b0c08c855680abba7126"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "b828b566c784ded99696b3f1f4f59f1a15ca7327e7ecfa6836492a4dfe7dd429"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c10a1feadfaef3dabefcb247efa88558b9274f54"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8267eb93d5a7005b058c9180b568360e57d659117aba3d7977374b3393c71c37"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df91cd490f43890fb436b92aa7eca89eb7728db2"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "cb0edd93a85fc2480d8b38addca694b6298223d92f24de6697c2ead0ee600d00"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5d0d4c5e6a12df6c0d3985742443e864f05761e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "69184196e7a6af92a432feaf30d081fcc70ec667ca2c736206bd1abfaf6630bf"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aa47a3440e94d50a50d6f26c837defda866a690"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d2a96677ce6b85129b4b11dc64f1f20e333909fa380347ad3162cd9959bd85fd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdc819986d985f6e71931921ff65a70020ddfa9a"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "33c42771a13c4bfdf7c76a8ca04df7bd77e51f89995efb5a8191826c28760d2d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a96715a80a0b4b3bcb654aa6d151455b7c1e04f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a8d087fc97909fd526539ec124aa1daaf88ecfa68bffde57d0045cc2812285e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a829c4b51e78ee8c75ea2e437289db53a90bed59"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bcb2b252ea2c1a9072bec73668786bc013edcad00a1586fb96400ab07ad1b176"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3023a79c1cdb0c1b2ce3ff8be54518b44bc7a51c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0a47173c173754d93e7ae2e4a60302c847064f0a3255502286d55523479a74fb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0df2c7d1dec917494aee69e3b3ea3a32b27f9c8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e49de6b6ee7efc4ca341c20557893cb9a81223a7d181040fcaa486defd7f8150"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75b4237c8f82574bd2cbe2894dd6b4c985842c23"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3303b9a5ae47a56b654ca0dd1552a460d83567fcf2d6ea4c8e2207451e568600"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e624d8aae3760f1484f886cc2833fb380c5b28e9"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3b954e21b29627cb7eefbfbe53584e46fff2752059c3a7f2c6a2d54641a6d6c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4755184eee694bb9080da6de6a138307876c65e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e6ee813ca35f2e6cdb15977368808d1810a67432a4f4167ef2eb308e9e9bfaf3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f138c3388d069f063b69e8f4eab682bbfb98d82"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b25e5ac801d3cff4ce9c16ad6db4d8704ecb0e43cbd072d215a771ef95f14688"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "daf4bce28f2d90ce84135279d5b093b8597ebc51"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "0bea37007b48dd024c28cee0ac6fc878b85936790685ac84372d934f090688ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b22c3caba31587aa5ca1c76dc86e494396e153f8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "6af2c04226cf83ea94f0d9cf2aff7321c07c9f0491a0fe50008a5b24bed14b15"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0218d4240836b8a8c51b59cfca00a654f0923ca0"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "45298a59beb118aac8eefd9e39a4b2647f8435a84856dde069089ce3b2a5fc70"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c88e227a7e1618409cd2fd2ec26934c04d58f02"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "97f385f57a7ece8a68f1b82c7392d02ce4a48292205e815fa40c0c048e638986"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d78231856ad3ac52c7228985bf20966ebffaecdf"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "b36e5c88a3d3dfd7317ae2ebd76c5aa3485a21178d2f789ef6cce545af75aed1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "509c338186602cee7102c9bf81b72a2f3f062b5f"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "ef6f0ff85188be7721022c2371f9a5a481e2812ec1e96146ee4a1f7e271af5f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a63f44d3f6f75ab41faa9fee8e0bedfb9889837"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dedcf2a5a7a627141d879185e2c9356128f9d074b7b42030984830e9f5624888"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "13244211cca2af2159bb9c920bdbc16f42b3e80a"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "28bad80ef8f3bd74945cd4eb04cdc1355135129eb7e0d30a468c3513811aca1d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1022d1bc8e73747c2d8649a4bb46e3e37c3c6eb0"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "bbc4f432b91fb8c9b23b20a87c0dc36b252ac37962e3a59d5af27deccf6c3f8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "726c2000b79e599ca1919e371a7ef49edcdffbad"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "82770db013d1f58fc500046f2c73c6fd57a2b9983e346919ac884ad7b820aed0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac26e38a604e1eff139980182a05c7b63ac4d2fd"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7663cab8534d584ad993e31ac02e354d0deb39cd78844f5f7e542e31f9c60c7f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22224d355692daee122e32cd2df6e40ea6500aa8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "8a1c0a0b3cd2dbd1312458785492fef3fe5fa930bd477a1b7d049aaa587ede3e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "45454252a48f0cbed03653005faa35823ac3a758"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "563021dffa37d59f663b0b8c616086288ab33aaedd6f6a72b65f7e33a68e6c29"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "541d706aefc6a3ebc515be39e21c809b3f8dd37e"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "7bc63b6005238610fc89feb87cda6b0efa29a2aca4d8792fb18645ffebc9f027"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d77d53394f69cc4c0b1a7ef2c23e1c7499b6c7a"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "5e82bf3f6b405c5f6c13026304ce22ce03b4398e0aded80aa09d5c012bc168c4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v12.0.0+0/LLVM_assert.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
