[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "78f9a1879a6285b9443f0580efbf537f0b4ffd3c"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "9d50c76d2a928fd36d8d332b475f1be4badf846aba25e3d26486aee560c9e92d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d46f0166a3227b49eccf8008aa2dcdf756e8430"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7f3e8f2b49067c2f2317dea2ca37a3a5e606d2b978b90a2fe26cea206d459370"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cddaff2c3f942b08f176d0167c23a3851ef208f5"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2f5c14da08b4c28e750002fe3bee06310851522d36ce8fc0379237ac4234061e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "059c4bf4a435ae675a3ebdc0b0815004ea51e1f2"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "5f6c5628e23765b3d8d707f5bfbd9dea5dc99597850a5d2ed05b186013706e17"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dd2a5a3f03b8f086e3b1a1dd93e9b614328e230"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "00ce7c12d2134c15f4f9c6b1b895a616f565a85123139f5c9c6b1d3a83e7fc50"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "080afe009d8c51d37cf94e792af829b1cefe82f7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "403ef8e4ecbb81d8d214cb76cccfdb6cb7f71500365b77d5da47dad2e0c62820"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "beea7f8c8ba5aff88d614e521f818823cb5176f7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "90d04ff63d40f824927a42ce7c94fcf32dce386d8c299bc6d7ec45ebfcd17801"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3dd6750e370146aa1243cbf02c0545b1fee8b1c"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "522b11907436f391c8be879e032a1ddd6a1d6cb692f6ee49ad6146e9ef846364"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6feb0957b1a5268335888bf1d32530edd589a15"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dec04032ceacb2936012e71cc7061636cde1a6aa327e1772dbcf0320285b8338"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "203c42a1627de3ca3fa8bcb7ac8a0d1f176adfe4"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a5fa1731958b54b4565962cd07e618ae9db2071e85c24ae59218b4ba87f647e2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7125cd385be9a673a117d2bf558534b493aafa8"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "9519ed3bc0be4f3075a9c62d0bddd9cbce04867da07d8d53fd8314d09a850860"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01da3027212c1e55471b2749da8f589b6baaea33"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "7733ae956ebdafa15f7e2d4103e7aa13d3b5224983d433b6d163d8fe9e2e308b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cdf64961b46baede27b0dbc4a8629cc0d02384d"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "de7641f931aa42cfa4900fe97aec3267f5f5ea67ccea157f7782407c69ded6db"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7f4899c67aac807aeccf673fa44d81b66e5870e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "10a9fb648686f6b5f54339268383fdc87ffdbf59ca5068c64547afa0dfe155c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b08ca56919d4a921eac1a34f0ab34d496495654d"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "fcefefcdac70fd26d4b8f1c7a4dcdecd7be389ea3a3dd95008dad7cb224d48c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2cb08ae4ed9477b7db00ec470f931b681cc1852"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "3d992528fe9156985713a5dc2d226d692575a5562e2e736c79d3bcd05557854e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ab2dc8268b27d6de2f372c66ed0530a96062e7f"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e3295e1b4f8918fa2abc911aca2869f48132aa42ceaa69fdba9cdaa38fe2e47d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb561ac1f89d4f9a41bc886b53ac0b360b4b9893"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "c381cf51b0c6139baaa49a4177f07dcb98db7c01fa7b7e7aaeace7e74ec1f568"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c6ec663036f5ab6a04c23c0aef85f7d06b41101"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "f467168fd5b19b925aa14284899792538dd128647d02c20fbc64dca3341ebb8c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d689267e68837d777eb1857a2d5c4db28aff48cc"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a8af30e7cc65b74124a3f299b008609f19b6357c363056eb96cd790d90818d5f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24e06fff2f650a36af23252f91c20a860fdc4ef1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "20c39b6d55887f67217297cd3519600c760969685014109e81e0e4a185f95791"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "c1f8ecb6ca5b3fff93dccdf9101552f329b36026"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "725e0104c531e38f7107e873a7629bfc5227cbbf2b1d035a0812f212d47bb724"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54662bd11166886fc304c62738ab6298b0eb31bf"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "d7e265ac073540a058535b840d578e22df82ad88b2c8b8669beae135a2fa44cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "624c69194ce77e51177632ac43abca217e1deb66"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c87810652969bb6908ec2deb1d0cf4dfb663ee011074bd4572998e5ed4684025"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87ff771ec59e7ff5321304bc7b95eee3de36ed08"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "803074c437d6ab944e5eb527027621c727ec2e502d1d7a66670901e1b7931031"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41e6562b73a27a54dbf9a40a282fc8a9f5baded4"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "c3b65c8dc4f4ca1341bd9faf28bf9a91c3fc21b69876d51d6274f47727c142c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "4cad8b77b2412ac0a6621a93f7c92f3c34cda7d9"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "2042aced3b1a63b1cdf27c63ef87f84e73e31bcec91aa2befbaa12c97958686c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a61e2ba246342ac4c570d1c5cd79868e1aec4ac"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "9f7932c2911e3da73370090ee86c1ca9dfad58322d123468513c52c07caba40c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "829cea484d8303110ce41af2efea1ecdc18e5074"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "249584dbace930a81b74632b98d6903ba5b106288d49fa6dd42a7326077d9d71"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.1+0/LLVM_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
