[[LLVM_assert]]
arch = "aarch64"
git-tree-sha1 = "5863957b2d8782cca4271dbfa3acc630f9c90471"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "7376f1b42cc10c9ac9b3dc866e9effcd39b211287dca18dc54cdd772bec0978b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.aarch64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ded39d0c6ad7d3ed78ec7c59a7999b2a62ac6c26"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "91988e10059c088a4749f83a2eda0fc343a2669050c4ff8e035d18b56c80d23a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4dee67b12a025d00cc606423891f3a21d162d34"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "11a23a3cd987f081316b917dd15d3b0e17d8eef0f6c270bf1a459b330c26b18f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a90fec816275c3e7810dab4da836b0e7db529e66"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "681c38511776048070f13299f135ca57d188ac65ed4d1803d9c7642fe0f4b248"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "844faa726800409a29f8e70bb661936a2719a10f"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "acdb937416fa5cc1a47fb70e439eb154a8f83b969b525be8041ba575d7127f95"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4601cf9361f0d9f2d869f53f86b8af66e81628c"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b457fdc985a6364447c406af093a8f43760e6e644c118ba31c40855c44609bec"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "853f52664e03d164a7fef77b4f0056f4d28265d1"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1b804fcd7bac30680d7d1f66c451d164bfe65dea1530cf620b1eb1340ef6f85a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9f62f4e8b517d74b1439135d28cf2d56b1741a7"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "82f22d8a6e65992d1d5922e8a110cd0cb692f05e388726adbb12ada02f5dd6ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3477e4dc42a9bb56333232bb8217c3fd5ea48541"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "a975a753291526f69545cb1b25f34cd2be5f0faac52a7e335daaf47c3a42ffc8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e37daaf2e8463c30b78131b09d957bb523e41e75"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e8ea2f82710817cdf38b8a485f094b6ed93f393c5f01d1ae77dfbba92ca7a96e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a30836ebfb3c9f11fa643eafc9f38bfa655949ab"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "2e41d11f7f2659cabf8d7f3373cec9f2b47e62ae415e28381d1fb62a7d781b16"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1ca34ad75c781265cc348de619d5e65d96f301e"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "15f39583a30e3e1711d6486cc5376c8e6c18baf70f08382f068e2763aac8b9d0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LLVM_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6ec6cd70fb903563c96cc4b175f5ce8d98c1705"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "dab838a66f9adb4f999629e767baa3897d4c59a9fbd27a1353f7caee83860488"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1eb081c335b6856114c0725a76c16eaee7ae028e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "56f0d7d088310137f1bb29eca8f94670db91045d9281c60cd936f55fc05d7cef"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9caef3827e109792e251116092505915014dd4ae"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "013f3d52c2832087d89076e53a10a28dd4f70631705382504502331d291b113e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31f2e774e1d2569a9c03277dbea07f58c1694d72"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "b0743dec88886c8b2fd5006a4f230ee2f2de1d8fbfc7e0dfa10d2a39b05a1517"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536abdf59e27d34105dd79cdcb8806f0ddaf14f3"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "f25601bba672a458559714d64d0b8f10c497edda8ff25f194b0f95f86d5d105c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae7712c3ab4d9c65c97bd2a800843b8f7d105e6e"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "94b26746a1501cdf7f248a2c167665397d046721097b013557c9dec786aebfd1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af86cbc30b67c74c866900c73c2d3a694f33f1e6"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "aace29a5a436397265c06f72175376a82e29f6a8fcdb2300ed19b6fb7aa39fa9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1978982484bbe1a6eb7180fa267f99ab54c0711"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "aed87f1135d9e8cb69fe541545eeb66b14512a71384b4acaa7c35bf25595c45f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db1797e10273808e9457fb44bd0eaa2035fa507e"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "219ddbddb464c9cc8bd3b63a06588ac9d84f9a605d69999bab86c8e2df61d7f9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "f93be7b3ae0d0e7a9fe37f5d0cca9993403dd6b9"
os = "macos"

    [[LLVM_assert.download]]
    sha256 = "dfa11b01cc1a799ce06566cae18b6a60186df5ed59093212c7f90fb43578d118"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-apple-darwin.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41425a73a670713d24bd8b1c72db81ba995f3eb4"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "114afab355429e254e6888615cfde369ca6598e7516b8d24c44514eae8f399ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b6dd3551cddf118aece9fb33ff924570c0e25f7"
libc = "glibc"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "229507fd452c61aec0496ca746419417b5b218d8d2de3c584fa967b25d522a04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e594082b39a20d37bd1ab088b32afc0e0d19ea8"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "e7ec3b606e18aa4d1edda9b51c3be8056421bfb08bd81ee9835d90d1734becba"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe5624d19562a9696300fe41aa3e1286a28bba01"
libc = "musl"
os = "linux"

    [[LLVM_assert.download]]
    sha256 = "1584e1feed1743ecdaceac4bbd65507bb9053adc9601aabc8aed464a08dd2fdc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
git-tree-sha1 = "a414127a44f0ae72ca06346c5928765a7572111f"
os = "freebsd"

    [[LLVM_assert.download]]
    sha256 = "a22e23cbead731d8c8fdc3f99d76cf8dba45d29e89bf453b2924e62568d21e41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d0b99bb27f00f3e1e5c32e6aac0cd09efb29d5f"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "0cbde4d1b98080e4a82ec5dff30721f72bdb97dea4c887e9b28d522c53143d5d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LLVM_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fabdea12a02c2ac8b13d43a9f53928be83d71f68"
os = "windows"

    [[LLVM_assert.download]]
    sha256 = "d21d495214642a2115a5202348ef192fd295f9d7251d30ec5607fb24d2e5b38d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_assert_jll.jl/releases/download/LLVM_assert-v13.0.0+2/LLVM_assert.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
